version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm run migrate && npm start"